shell = "zsh"

[plugins]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
use = ["{{ name }}.zsh"]

#[plugins.zsh-syntax-highlighting]
#github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-fast-syntax]
github = "zdharma/fast-syntax-highlighting"

[plugins.prompt]
github = "zap-zsh/zap-prompt"

[plugins.vim]
github = "softmoth/zsh-vim-mode"

[plugins.256color]
github = "chrissicool/zsh-256color"

[plugins.base16]
github = "chriskempson/base16-shell"
